### ISSUE TITLE
Support for Keyboard Shortcuts on Non-English Keyboards

### ISSUE THREAD

**Issue by MartinNiederl** [nizioleque/youtube-custom-speed#1]
The current implementation uses the `key` property of `KeyboardEvent` to detect key presses. This approach works well for English keyboards but causes issues on non-English keyboards, such as German keyboards, where the physical keys do not produce the same characters.

For example:
- On English keyboards, `Shift` + `,` produces `<` and `Shift` + `.` produces `>`.
- On German keyboards, these combinations produce `;` and `:` respectively, leading to non-default shortcuts.

**Exemplary Solution:**

https://github.com/nizioleque/youtube-custom-speed/compare/master...MartinNiederl:youtube-custom-speed:master

A more robust solution would be to listen to the physical keys instead:

```js
document.body.addEventListener('keydown', e => {
    if (e.shiftKey && e.code === 'Period') {
        e.preventDefault();
        e.stopPropagation();
        kbshort(true);
    }
    else if (e.shiftKey && e.code === 'Comma') {
        e.preventDefault();
        e.stopPropagation();
        kbshort(false);
    }
}, { capture: true });
```

**Comment by nizioleque** [comment]
Hi, I'm sorry it took me so long to respond. Thank you for the feedback, can you make a pull request? I'll merge it and I can release an update to the store.

Also, why did you add `preventDefault`? What behavior are you trying to prevent, typing the character?

**Comment by MartinNiederl** [comment]
I removed the `preventDefault`. Not sure why I included it in the first place.
